
export const GET_BANNER_DATA_START = 'GET_BANNER_DATA_START'
export const GET_BANNER_DATA_SUCCESS = 'GET_BANNER_DATA_SUCCESS'
export const GET_BANNER_DATA_ERROR = 'GET_BANNER_DATA_ERROR'


export const GET_CARD_DATA_START = 'GET_CARD_DATA_START'
export const GET_CARD_DATA_SUCCESS = 'GET_CARD_DATA_SUCESS'
export const GET_CARD_DATA_ERROR = 'GET_CARD_DATA_ERROR'